export * from './deleteNewsLetter.js'
export * from './getNewsLetter.js'
export * from './patchNewLetter.js'
export * from './postNewLetter.js'
export * from './udpateNewLetter.js'
export * from './getOneAndReplace.js'
